<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-TennisBooking-267f185d-2ea4-4bb2-a032-ea4d8e31948b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.20" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.20" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.15.1" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.15.1" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.15.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Migrations\" />
    <Folder Include="Services\" />
    <Folder Include="Repository\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

</Project>
